-- Script de Migración Manual para el Módulo de Nutrición Deportiva
-- Fecha: 2026-02-07

-- 1. Actualizar tabla 'alumnos'
ALTER TABLE public.alumnos ADD COLUMN IF NOT EXISTS horario_entrenamiento text;
ALTER TABLE public.alumnos ADD COLUMN IF NOT EXISTS intolerancias text;
ALTER TABLE public.alumnos ADD COLUMN IF NOT EXISTS horas_sueno numeric;
ALTER TABLE public.alumnos ADD COLUMN IF NOT EXISTS agua_diaria text;
ALTER TABLE public.alumnos ADD COLUMN IF NOT EXISTS digestion text;
ALTER TABLE public.alumnos ADD COLUMN IF NOT EXISTS lesiones_recientes text;

-- 2. Actualizar tabla 'historial_medico'
ALTER TABLE public.historial_medico ADD COLUMN IF NOT EXISTS porcentaje_grasa numeric;
ALTER TABLE public.historial_medico ADD COLUMN IF NOT EXISTS porcentaje_musculo numeric;
ALTER TABLE public.historial_medico ADD COLUMN IF NOT EXISTS grasa_visceral numeric;
ALTER TABLE public.historial_medico ADD COLUMN IF NOT EXISTS cintura numeric;
ALTER TABLE public.historial_medico ADD COLUMN IF NOT EXISTS cadera numeric;
ALTER TABLE public.historial_medico ADD COLUMN IF NOT EXISTS brazo_relajado numeric;
ALTER TABLE public.historial_medico ADD COLUMN IF NOT EXISTS brazo_contraido numeric;
ALTER TABLE public.historial_medico ADD COLUMN IF NOT EXISTS muslo numeric;

-- 3. Crear tabla 'bioquimica'
CREATE TABLE IF NOT EXISTS public.bioquimica (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id integer NOT NULL,
    fecha_toma timestamp with time zone NOT NULL,
    hemoglobina numeric,
    hematocrito numeric,
    glucosa_basal numeric,
    colesterol_total numeric,
    trigliceridos numeric,
    vitamina_d numeric,
    ferritina numeric,
    observaciones text,
    created_at timestamp with time zone,
    created_by text,
    updated_at timestamp with time zone,
    updated_by text,
    fecha_anulacion timestamp with time zone,
    usuario_anulacion text,
    CONSTRAINT fk_bioquimica_alumnos_alumno_id FOREIGN KEY (alumno_id) REFERENCES public.alumnos (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_bioquimica_alumno_id ON public.bioquimica (alumno_id);

-- 4. Crear tabla 'plan_nutricional'
CREATE TABLE IF NOT EXISTS public.plan_nutricional (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id integer NOT NULL,
    fecha_inicio timestamp with time zone NOT NULL,
    fecha_fin timestamp with time zone,
    objetivo text,
    tmb numeric,
    gasto_energetico_total numeric,
    proteinas integer,
    carbohidratos integer,
    grasas integer,
    observaciones text,
    archivo_ruta text,
    created_at timestamp with time zone,
    created_by text,
    updated_at timestamp with time zone,
    updated_by text,
    fecha_anulacion timestamp with time zone,
    usuario_anulacion text,
    CONSTRAINT fk_plan_nutricional_alumnos_alumno_id FOREIGN KEY (alumno_id) REFERENCES public.alumnos (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_plan_nutricional_alumno_id ON public.plan_nutricional (alumno_id);

-- 5. Crear tabla 'suplementacion'
CREATE TABLE IF NOT EXISTS public.suplementacion (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_nutricional_id integer NOT NULL,
    producto text NOT NULL,
    dosis text,
    momento text,
    observaciones text,
    created_at timestamp with time zone,
    created_by text,
    updated_at timestamp with time zone,
    updated_by text,
    fecha_anulacion timestamp with time zone,
    usuario_anulacion text,
    CONSTRAINT fk_suplementacion_plan_nutricional_plan_nutricional_id FOREIGN KEY (plan_nutricional_id) REFERENCES public.plan_nutricional (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_suplementacion_plan_nutricional_id ON public.suplementacion (plan_nutricional_id);
